/*
 Copyright (c) 2026 Ashraf Morningstar
 These are personal recreations of existing projects, developed by Ashraf Morningstar
 for learning and skill development.
 Original project concepts remain the intellectual property of their respective creators.
 Repository: https://github.com/AshrafMorningstar
*/

import { AbsoluteFill, Sequence, useVideoConfig } from "remotion";
import React from "react";
import { DeveloperData } from "../types";
import { CodeDNA } from "./CodeDNA";
import { RPGHeroStats } from "./RPGHeroStats";
import { SkillsUniverse3D } from "./SkillsUniverse3D";
import { ProjectShowcase } from "./ProjectShowcase";
import { TimeLapseEvolution } from "./TimeLapseEvolution";
import { StrategicInsights } from "./StrategicInsights";
import { themes, ThemeType } from "../styles/themes";
import { cn } from "../utils/cn";

interface MainSequenceProps {
  data: DeveloperData;
  theme?: ThemeType;
}

export const MainSequence: React.FC<MainSequenceProps> = ({
  data,
  theme = "cyberpunk",
}) => {
  const { fps } = useVideoConfig();
  const currentTheme = themes[theme] || themes.cyberpunk;

  // Scene Durations (in frames)
  const SCENE_DURATION = 300; // 10 seconds at 30fps

  return (
    <AbsoluteFill className={currentTheme.background}>
      {/* Dynamic Background based on theme */}
      <div className={cn("absolute inset-0", currentTheme.gridOpacity)}>
        <div
          className={cn(
            "absolute inset-0 bg-[size:50px_50px]",
            currentTheme.gridColor
          )}
        />
      </div>

      <Sequence
        from={0}
        durationInFrames={SCENE_DURATION}
        name="Intro: Code DNA"
      >
        <CodeDNA data={data} />
        {/* Cinematic Title Overlay */}
        <AbsoluteFill className="justify-center items-center pointer-events-none">
          <h1
            className={cn(
              "text-9xl font-black opacity-0 animate-[fadeIn_2s_ease-out_forwards]",
              currentTheme.accentText
            )}
          >
            DEV METRICS
          </h1>
        </AbsoluteFill>
      </Sequence>

      <Sequence
        from={SCENE_DURATION}
        durationInFrames={SCENE_DURATION}
        name="Stats: RPG Profile"
      >
        <RPGHeroStats data={data} />
      </Sequence>

      <Sequence
        from={SCENE_DURATION * 2}
        durationInFrames={SCENE_DURATION}
        name="Skills: 3D Universe"
      >
        <SkillsUniverse3D data={data} />
      </Sequence>

      <Sequence
        from={SCENE_DURATION * 3}
        durationInFrames={SCENE_DURATION}
        name="Projects: Showcase"
      >
        <ProjectShowcase data={data} />
      </Sequence>

      <Sequence
        from={SCENE_DURATION * 4}
        durationInFrames={SCENE_DURATION}
        name="Strategy: Insights"
      >
        <StrategicInsights data={data} />
      </Sequence>

      <Sequence
        from={SCENE_DURATION * 5}
        durationInFrames={SCENE_DURATION}
        name="Contributions: Evolution"
      >
        <TimeLapseEvolution data={data} />
      </Sequence>

      {/* Outro */}
      <Sequence from={SCENE_DURATION * 6} durationInFrames={150} name="Outro">
        <AbsoluteFill
          className={cn("items-center justify-center", currentTheme.background)}
        >
          <h2
            className={cn(
              "text-6xl font-black tracking-widest uppercase",
              currentTheme.textPrimary
            )}
          >
            Build. Ship. Evolve.
          </h2>
          <p className={cn("mt-4 font-mono", currentTheme.textSecondary)}>
            Generated by DevMetrics Pro AI
          </p>
        </AbsoluteFill>
      </Sequence>
    </AbsoluteFill>
  );
};
